# After 1.3.17 and before version 1.4.0
# This file is a command execution file generated by the command assistant. 
# Do not edit it.

from bdpyconsts import bdpyconsts as pyconst

# Command Description Information
_BDCMD_DESC_ = {
    "name":'time_print_2',
    "alias":'time_print_v2',
    "desc":'time_print_v2'
}

if pyconst._BD_CMD_RUN_NOW == True:
    from bdpycmd.cmd.factory.base import BaseCommand 
    from ..script.time_print import time_print

    class Command(BaseCommand,time_print):
        def __init__(self):
            super().__init__(name=__class__.__module__,alias='time_print_v2',description='time_print_v2')
            super(BaseCommand,self).__init__()
            